name: RELEASE new minor
on:
  push:
    branches:
      - release
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - uses: fwilhe2/bump-version@main
        id: bump
      - run: echo ${{ steps.bump.outputs.newVersion }}
