name: RELEASE new minor
on:
  push:
    branches:
      - release
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: my-step
        run: echo "Hello World!"
      - name: Get Version Number
        uses: fwilhe2/bump-version@main
        id: bump
        with:
          component: minor
      - run: echo New Version Number ${{ steps.bump.outputs.newVersion }}
